source 'https://rubygems.org'

gem 'rails', '~> 8.1.2'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'jwt'
gem 'httparty'
gem 'bcrypt', '~> 3.1.7'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails'
  gem 'webmock'
  gem 'simplecov', require: false
end

group :development do
  gem 'rubocop-rails-omakase', require: false
end
